### ISSUE TITLE
https://worldaeropresschampionship.wordpress.com down

### ISSUE THREAD

**Issue by simao** [tedmiston/aeropress#14]
Anybody knows a mirror?

**Comment by tedmiston** [comment]
As of this morning, it appears to be back online! 👍

**Comment by simao** [comment]
Still down for me.. It shows a page with "protected blog" and a form for user/pass

**Comment by tedmiston** [comment]
Ah, you're right.  I misread this as being about http://www.worldaeropresschampionship.com the first time.

**Comment by tedmiston** [comment]
It looks like they're not available on archive.org.

I've sent a tweet their way hoping to figure it out. 

https://twitter.com/kicksopenminds/status/838069805592809476

**Comment by tedmiston** [comment]
I'm closing this for now since they didn't respond on Twitter.  Hoping a mirror or cached version will appear in the future.  It seems like changing the blog to "private" was / is a mistake on their end.
